package br.furb.programcaoii.problema2.view;

import br.furb.programcaoii.problema2.model.Cliente;
import br.furb.programcaoii.problema2.model.ClientePessoaFisica;
import br.furb.programcaoii.problema2.model.ClientePessoaJuridica;
import br.furb.programcaoii.problema2.controller.ClienteController;
import br.furb.programcaoii.problema2.factory.ControllerFactory;
import java.text.ParseException;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ariel
 */
public class ClienteView extends javax.swing.JFrame implements View<Cliente> {

    private Cliente cliente;
    private MaskFormatter mascaraCNPJ = null;
    private MaskFormatter mascaraCPF = null;
    private MaskFormatter mascaraTelefoneFixo = null;
    private MaskFormatter mascaraTelefoneCelular = null;

    private void habilitarDesabilitarServidorJMS() {
        txtServidorJMS.setVisible(rbPessoaJuridica.isSelected());
        lblServidor.setVisible(rbPessoaJuridica.isSelected());
    }

    private void alterarMascaraCPFCNPJ(String tipoPessoa) {
        if (tipoPessoa.equalsIgnoreCase("PF")) {
            mascaraCPF.install(txtCpfCnpj);
        } else if (tipoPessoa.equalsIgnoreCase("PJ")) {
            mascaraCNPJ.install(txtCpfCnpj);
        }
    }

    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        initComponents();
        this.setTitle("Cliente | FastMoney");
        habilitarDesabilitarServidorJMS();

        try {
            // criando máscaras
            mascaraCNPJ = new MaskFormatter("##.###.###/####-##");
            mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraTelefoneFixo = new MaskFormatter("(##) ####-####");
            mascaraTelefoneCelular = new MaskFormatter("(##) #####-####");
        } catch (ParseException exc) {
        }

        rbPessoaFisica.setSelected(true);
        mascaraTelefoneFixo.install(txtTelefoneFixo);
        mascaraTelefoneCelular.install(txtTelefoneCelular);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbPessoaFisica = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbPessoaJuridica = new javax.swing.JRadioButton();
        btSalvar = new javax.swing.JButton();
        lblServidor = new javax.swing.JLabel();
        txtServidorJMS = new javax.swing.JTextField();
        txtCpfCnpj = new javax.swing.JFormattedTextField();
        txtTelefoneFixo = new javax.swing.JFormattedTextField();
        txtTelefoneCelular = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nome");

        txtNome.setName(""); // NOI18N

        jLabel2.setText("Telefone fixo");

        jLabel3.setText("Telefone celular");

        jLabel4.setText("CPF/CNPJ");

        rbPessoaFisica.setText("Pessoa física");
        rbPessoaFisica.setRolloverEnabled(false);
        rbPessoaFisica.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbPessoaFisicaStateChanged(evt);
            }
        });

        jLabel5.setText("Tipo pessoa");

        rbPessoaJuridica.setText("Pessoa jurídica");
        rbPessoaJuridica.setRolloverEnabled(false);
        rbPessoaJuridica.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbPessoaJuridicaStateChanged(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        lblServidor.setText("Servidor JMS");

        txtCpfCnpj.setToolTipText("");
        txtCpfCnpj.setName("txtCpfCnpj"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCpfCnpj)
                    .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbPessoaFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(rbPessoaJuridica))
                    .addComponent(txtServidorJMS)
                    .addComponent(txtTelefoneFixo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(lblServidor))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTelefoneCelular))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPessoaFisica)
                    .addComponent(rbPessoaJuridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblServidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtServidorJMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            if (null == cliente) {
                if (rbPessoaFisica.isSelected()) {
                    ClientePessoaFisica clientePessoaFisica = new ClientePessoaFisica(txtNome.getText(), txtTelefoneCelular.getText(), txtTelefoneFixo.getText(), txtCpfCnpj.getText());
                    cliente = clientePessoaFisica;
                } else if (rbPessoaJuridica.isSelected()) {
                    ClientePessoaJuridica clientePessoaJuridica = new ClientePessoaJuridica(txtNome.getText(), txtTelefoneCelular.getText(), txtTelefoneFixo.getText(), txtCpfCnpj.getText(), txtServidorJMS.getText());
                    cliente = clientePessoaJuridica;
                } else {
                    throw new RuntimeException("Selecione o tipo de pessoa");
                }
            } else {
                cliente.setNome(txtNome.getText());
                cliente.setTelCelular(txtTelefoneCelular.getText());
                cliente.setTelFixo(txtTelefoneFixo.getText());
                if (cliente instanceof ClientePessoaFisica) {
                    ((ClientePessoaFisica) cliente).setCpf(txtCpfCnpj.getText());
                } else {
                    ((ClientePessoaJuridica) cliente).setCnpj(txtCpfCnpj.getText());
                }
            }

            ControllerFactory.getController(ClienteController.class).salvar(cliente);
            this.setVisible(false);
        } catch (Exception e) {
            abrirDialogoErro(this, e);
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void rbPessoaFisicaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbPessoaFisicaStateChanged
        if (rbPessoaFisica.isSelected()) {
            rbPessoaJuridica.setSelected(!rbPessoaFisica.isSelected());
            rbPessoaFisica.setSelected(true);
        }
        alterarMascaraCPFCNPJ("PF");
        habilitarDesabilitarServidorJMS();
    }//GEN-LAST:event_rbPessoaFisicaStateChanged

    private void rbPessoaJuridicaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbPessoaJuridicaStateChanged
        if (rbPessoaJuridica.isSelected()) {
            rbPessoaFisica.setSelected(!rbPessoaJuridica.isSelected());
            rbPessoaJuridica.setSelected(true);
        }
        alterarMascaraCPFCNPJ("PJ");
        habilitarDesabilitarServidorJMS();
    }//GEN-LAST:event_rbPessoaJuridicaStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblServidor;
    private javax.swing.JRadioButton rbPessoaFisica;
    private javax.swing.JRadioButton rbPessoaJuridica;
    private javax.swing.JFormattedTextField txtCpfCnpj;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtServidorJMS;
    private javax.swing.JFormattedTextField txtTelefoneCelular;
    private javax.swing.JFormattedTextField txtTelefoneFixo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setEntidade(Cliente entidade) {
        this.cliente = entidade;

        txtNome.setText(cliente.getNome());
        txtTelefoneCelular.setText(cliente.getTelCelular());
        txtTelefoneFixo.setText(cliente.getTelFixo());

        rbPessoaJuridica.setEnabled(false);
        rbPessoaFisica.setEnabled(false);

        if (cliente instanceof ClientePessoaFisica) {
            ClientePessoaFisica clientePessoaFisica = (ClientePessoaFisica) cliente;
            rbPessoaFisica.setSelected(true);
            txtCpfCnpj.setText(clientePessoaFisica.getCpf());
        } else if (cliente instanceof ClientePessoaJuridica) {
            ClientePessoaJuridica clientePessoaJuridica = (ClientePessoaJuridica) cliente;
            rbPessoaJuridica.setSelected(true);
            txtCpfCnpj.setText(clientePessoaJuridica.getCnpj());
            txtServidorJMS.setText(clientePessoaJuridica.getServidorJMS());
        }

    }
}
